rootFolder = fullfile('CorelDB');
imgSets = [ imageSet(fullfile(rootFolder, '2_building')), ...
            imageSet(fullfile(rootFolder, '3_buses')), ...
            imageSet(fullfile(rootFolder, '4_dinasours')),...
            imageSet(fullfile(rootFolder, '5_elephants')),...
            imageSet(fullfile(rootFolder, '6_flowers')),...
            imageSet(fullfile(rootFolder, '7_horses')),...
            imageSet(fullfile(rootFolder, '8_mountains')),...
            imageSet(fullfile(rootFolder, '9_foods'))];
               
no_classes = length(imgSets);
featureOption = 'bagOfWords';

sfs = [0.2,0.3,0.5,0.7,0.8];
for i=1:length(sfs)
    imgSetsForBag = partition(imgSets, 30, 'randomize');
    bag = bagOfFeatures(imgSetsForBag,...
                    'VocabularySize' ,200,...
                    'StrongestFeatures',sfs(i));
    save(['bag strongest feature ',num2str(sfs(i)),'.mat'],'bag');
end


vss = [20,50,70,100,200,300];
for i=1:length(sfs)
    imgSetsForBag = partition(imgSets, 30, 'randomize');
    bag = bagOfFeatures(imgSetsForBag,...
                    'VocabularySize' ,vss(i),...
                    'StrongestFeatures',0.5);
    save(['bag vocab size ',num2str(vss(i)),'.mat'],'bag');
end